"""fix leads table on uniqueness

Revision ID: 78fe2fb7ad1b
Revises: 9323511f8848
Create Date: 2022-02-14 20:55:52.382972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fe2fb7ad1b'
down_revision = '9323511f8848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'leads', ['phone'])
    op.create_unique_constraint(None, 'leads', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_constraint(None, 'leads', type_='unique')
    # ### end Alembic commands ###
